<?php

/**
 * @file
 * Replicate date module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function replicate_date_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    // Main module help for the replicate_date module.
    case 'help.page.replicate_date':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides the ability to replicate nodes using the Replicate API.') . '</p>';

    default:
  }

  return $output;
}
